config/routes.rb
Rails.application.routes.draw do
  devise_for :teachers
  devise_for :students, :controllers => {:registrations => "students/registrations"}
  resources :teachers, only: [:show]
  resources :students, only: [:show]
  resources :courses
  resources :attendances
  resources :subjects
  resources :learning
  get 'home/index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: "home#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/attendance.rb
class Attendance < ApplicationRecord
	belongs_to :students, optional: true
	belongs_to :courses, optional: true
end

app/models/course.rb
class Course < ApplicationRecord
	has_many :attendances, through: :attendances
	belongs_to :teacher 
	belongs_to :subject 
end

app/models/learning.rb
class Learning < ApplicationRecord
	belongs_to :student 
	belongs_to :course
end

app/models/student.rb
class Student < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  has_many :attendances, through: :attendances
  has_one :student_name, through: :student_names
  has_many :learnings, through: :learnings
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/subject.rb
class Subject < ApplicationRecord
	has_many :courses, dependent: :destroy
	has_many :teacher, through: :courses
end

app/models/teacher.rb
class Teacher < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/courses_controller.rb
class CoursesController < ApplicationController
  def index
    @courses = Course.all()
  end

  def show
    @course = Course.find(params[:id])
    @learnings = Learning.where(course_id: @course.id )
  end

  def new
    @course = Course.new
  end

  def create
    @course = Course.create(subject_id: course_params[:subject_id],teacher_id: current_teacher.id,classes:0)
    redirect_to course_path(id: @course.id)
    # redirect_to assignment_path(question_params[:assignment_id])
  end

  def delete
  end

  def destroy
  end
  private

  def course_params
    params.require(:course).permit(:subject_id)
  end  
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/learning_controller.rb
class LearningController < ApplicationController
  def new
    @learning = Learning.create(:course_id => params[:course_id], :student_id => params[:student_id]  )
    redirect_to new_attendance_path(course_id: @learning.course_id,student_id: @learning.student_id)
  end
end

app/controllers/students_controller.rb
class StudentsController < ApplicationController
  def show
  end
end

app/controllers/subjects_controller.rb
class SubjectsController < ApplicationController
  def index
  end

  def edit
  end

  def new
    @subject = Subject.new
  end

  def create
    @subject = Subject.create(subject_name: subject_params[:subject_name])
    @course = Course.create(subject_id: @subject.id, teacher_id: current_teacher.id, classes: 0)
    redirect_to course_path(@course.id)
  end

  def delete
  end
  def destroy
  end
  private

  def subject_params
    params.require(:subject).permit(:subject_name)
  end  
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/attendance_helper.rb
module AttendanceHelper
end

app/helpers/course_helper.rb
module CourseHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/learning_helper.rb
module LearningHelper
end

app/helpers/lecture_helper.rb
module LectureHelper
end

app/helpers/student_helper.rb
module StudentHelper
end

app/helpers/subject_helper.rb
module SubjectHelper
end

app/helpers/teacher_helper.rb
module TeacherHelper
end

app/views/courses/index.html.erb
<% if teacher_signed_in? %>
<a class="btn btn-secondary my-3" href="<%= new_course_url()%>" role="button">New Course </a>
<% if not @courses.nil? %>
<ul class="list-group py-5" >
	<% @courses.each do |course| %>
		<% @subject = Subject.find(course.subject_id)%>
			<div class="col-sm-4">
				<div class="card mb-4 shadow-sm">
					<div class="card-body">
						<p class="card-text"><%= @subject.subject_name %></p>
						<div class="d-flex justify-content-between align-items-center">
							<div class="btn-group">
								<button type="button" class="btn btn-sm btn-outline-secondary" onclick="location.href = '<%=course_path(course.id)%>'">Take Attendance</button>
							</div>
							<small class="text-muted"><%= course.classes%>classes</small>
						</div>
					</div>
				</div>
			</div>
	<% end %>
</ul>
<% else %>
<h2>Wow Such Empty</h2>
<% end %>
<% else %>
<h2><a href="<%= new_admin_session_path%>">
	<i class="fa fa-sign-in"></i> Login as Admin 
</h2>
<% end %>

app/views/courses/new.html.erb
<!-- <h2 class="my-4" style="font-family: Courier New;">Select Subject : </h2> -->
<%= form_for @course do |f| %>
<br>
<%= f.label :subject,"select subject"%>
<%= f.collection_select :subject_id, Subject.all, :id, :subject_name%>
<br>
<%= f.submit%>
<%end%>
<br>
<a href ="<%= new_subject_url()%>" class="btn btn-secondary"> Add a custom subject </a>

app/views/courses/show.html.erb
<% if teacher_signed_in?%>
<% if not @learnings.nil?%>
<b>Students Enrolled:</b>
<br>
<%end%>
<% @learnings.each do |lecture| %>
	<% @student = Student.find(lecture.student_id)%>
	<%= @student.first_name %>
	<br>
<%end%>	
<%= form_tag(edit_attendance_url, id: "a" ,method: "get")%>
	<%#= hidden_field_tag(student_id,value = "Present") %>
	<%= hidden_field_tag(:id,value = @course.id) %>
	<% params.merge(:id => @course.id) %>
	<% if not @learnings.nil?%>
		<input id="attendance" disabled = "true" class= "btn btn-primary my-2"name="commit" type="submit" value="Submit" data-disable-with="Submit" />
	<% end %>
<% end %>
<script type="text/javascript">
function checkStatus(){
	document.querySelector("#attendance").disabled = false
	fetch('https://sidhy-33818.firebaseio.com/.json')
	  .then(response => {
	    return response.json()
	  })
	  .then(data => {
	    // Work with JSON data here
	    for (d in data){
			console.log(data[d])
	    	f = document.querySelector("#a")
	    	f.innerHTML+=(`<input type="hidden" name=${data[d]} value="Present"></input>`)
	    }
	  })
	  .catch(err => {
	    // Do something for an error here
	  })
	  
}
setTimeout(checkStatus,10)
</script>

<h2 class="my-4" style="font-family: Courier New;">Add Students : </h2>
<ul class="list-group my-5">
	<% Student.all.each do |student| %>
	<% @learning = Learning.where(student_id: student.id, course_id: @course.id).first%>
	<% if @learning.nil? %>
	<li class="list-group-item">
		<%= student.first_name %>
		<a href ="<%= new_learning_url(course_id: @course.id,student_id: student.id)%>" class="mx-4"> <i class="fa fa-plus" aria-hidden="true"></i>
		</a> 
	</li>
	<% end %>
</ul>
<% end %>
<%# Thread.new do %>
	<%#system("cd pys && python faceReco.py")%>
<%#end%>