config/routes.rb
Rails.application.routes.draw do
  devise_for :teachers
  devise_for :students, :controllers => {:registrations => "students/registrations"}
  resources :teachers, only: [:show]
  resources :students, only: [:show]
  resources :courses
  resources :attendances
  resources :subjects
  resources :learning
  get 'home/index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: "home#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/attendance.rb
class Attendance < ApplicationRecord
	belongs_to :students, optional: true
	belongs_to :courses, optional: true
end

app/models/course.rb
class Course < ApplicationRecord
	has_many :attendances, through: :attendances
	belongs_to :teacher 
	belongs_to :subject 
end

app/models/learning.rb
class Learning < ApplicationRecord
	belongs_to :student 
	belongs_to :course
end

app/models/student.rb
class Student < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  has_many :attendances, through: :attendances
  has_one :student_name, through: :student_names
  has_many :learnings, through: :learnings
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/subject.rb
class Subject < ApplicationRecord
	has_many :courses, dependent: :destroy
	has_many :teacher, through: :courses
end

app/models/teacher.rb
class Teacher < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/courses_controller.rb
class CoursesController < ApplicationController
  def index
    @courses = Course.all()
  end

  def show
    @course = Course.find(params[:id])
    @learnings = Learning.where(course_id: @course.id )
  end

  def new
    @course = Course.new
  end

  def create
    @course = Course.create(subject_id: course_params[:subject_id],teacher_id: current_teacher.id,classes:0)
    redirect_to course_path(id: @course.id)
    # redirect_to assignment_path(question_params[:assignment_id])
  end

  def delete
  end

  def destroy
  end
  private

  def course_params
    params.require(:course).permit(:subject_id)
  end  
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/learning_controller.rb
class LearningController < ApplicationController
  def new
    @learning = Learning.create(:course_id => params[:course_id], :student_id => params[:student_id]  )
    redirect_to new_attendance_path(course_id: @learning.course_id,student_id: @learning.student_id)
  end
end

app/controllers/students_controller.rb
class StudentsController < ApplicationController
  def show
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/attendance_helper.rb
module AttendanceHelper
end

app/helpers/course_helper.rb
module CourseHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/learning_helper.rb
module LearningHelper
end

app/helpers/lecture_helper.rb
module LectureHelper
end

app/helpers/student_helper.rb
module StudentHelper
end

app/helpers/subject_helper.rb
module SubjectHelper
end

app/helpers/teacher_helper.rb
module TeacherHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Attendance Manager</title>
    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <!--Navigation Bar-->
    <nav class="navbar navbar-light bg-light d-flex">
      <div class="container">
        <div class="logo">
          <a class="navbar-brand" href="/">
            <%= fa_stacked_icon "map", base: "circle_thin"%>
            Attendance Manager
          </a>
        </div>
        <div class="user-section">
          <% if teacher_signed_in? %>
            <a href="<%= teacher_path(current_teacher)%>" data-method="get">
              <i class="fa fa-user"></i>
            </a>
            <a href="<%= destroy_teacher_session_path%>" data-method="delete">
              <i class="fa fa-sign-out" aria-hidden="true"></i>
            </a>
          <% elsif student_signed_in? %>
            <a href="<%= student_path(current_student)%>" data-method="get">
              <i class="fa fa-user"></i>
            </a>
            <a href="<%= destroy_student_session_path%>" data-method="delete">
              <i class="fa fa-sign-out" aria-hidden="true"></i>
            </a>
          <% else %>
            <a href="<%= new_student_session_path%>">
              <i class="fa fa-sign-in"></i>  Student
            </a>
            <a href="<%= new_teacher_session_path%>">
              <i class="fa fa-sign-in"></i>  Teacher
            </a>
          <% end %>
        </div>
      </div>
    </nav>

    <!--Main content-->
    <main class="container" style="min-height: 786px">
      <%= yield %>
    </main>

    <!--Footer-->
    <footer class="container footer">
      <nav class="navbar d-flex">
        <ul>
          <li>ABOUT US</li>
        </ul>
        <p> © 2018 Attendance Manager </p>
      </nav>
    </footer>
  </body>
</html>